import type { Question } from "./types";

export const QUESTIONS: Question[] = [
  {
    id: "safety_now",
    type: "multi-safety",
    eyebrow: "ПЕРЕД НАЧАЛОМ",
    title: "КАК ТЫ ЧУВСТВУЕШЬ СЕБЯ ПРЯМО СЕЙЧАС?",
    description: "Отметь всё, что ощущаешь прямо сейчас. Если ничего не беспокоит — выбери первый вариант.",
    options: [
      { id: "clear", label: "Чувствую себя хорошо", detail: "Ничего не беспокоит, готов пройти тест" },
      { id: "pain", label: "Есть небольшой дискомфорт или напряжение", safetyFlag: "pain" },
      { id: "sharp", label: "Есть выраженная или резкая боль", safetyFlag: "sharp_pain" },
      { id: "numb", label: "Есть онемение или покалывание", safetyFlag: "numbness" },
      { id: "dizzy", label: "Есть головокружение", safetyFlag: "dizziness" },
      { id: "control", label: "Чувствую, что плохо контролирую движения", safetyFlag: "loss_of_control" },
    ],
  },
  {
    id: "body_map",
    type: "body-map",
    eyebrow: "Карта тела",
    title: "ГДЕ В ТЕЛЕ БОЛЬШЕ ВСЕГО НАПРЯЖЕНИЯ?",
    description: "Выберите одну область, которая чаще всего ощущается скованной, напряжённой или ограниченной в движении.",
    options: [
      { id: "none", label: "Нигде — тело ощущается свободно", score: 20 },
      { id: "neck", label: "Шея и плечи", score: 12 },
      { id: "back", label: "Верх спины и грудной отдел", score: 12 },
      { id: "pelvis", label: "Поясница и таз", score: 10 },
      { id: "knees", label: "Колени", score: 10 },
      { id: "feet", label: "Голеностопы и стопы", score: 10 },
      { id: "several", label: "Сразу несколько областей", score: 5 },
    ],
  },
  {
    id: "breath360",
    type: "video",
    videoId: "breath360",
    zone: "breath",
    maxScore: 12,
    eyebrow: "01 · ДЫХАНИЕ",
    title: "Дыхание 360°",
    description: "Сделайте 3 спокойных вдоха и наблюдайте, как двигаются рёбра и живот. Не старайтесь ничего исправлять.",
    instructions: ["Положите ладони на нижние рёбра", "Вдохните носом без подъёма плеч", "Оцените движение рёбер вперёд, в стороны и назад"],
    watchFor: "Рёбра расширяются вперёд, в стороны и назад, а шея и плечи остаются расслабленными.",
    helperText: "Не уверены в ответе? Выберите «Не смог оценить» — это не помешает получить результат.",
    options: [
      { id: "full", label: "Дыхание объёмное и свободное", detail: "Рёбра расширяются в разные стороны", score: 12 },
      { id: "partial", label: "Дыхание есть, но движение неравномерное", detail: "Одна сторона двигается заметно меньше", score: 8, asymmetry: true },
      { id: "upper", label: "В основном поднимаются грудь и плечи", score: 4 },
      { id: "hard", label: "Дышать тяжело или напряжённо", score: 2 },
      { id: "unknown", label: "Не смог оценить", detail: "Это нормально — просто переходите дальше", score: 6 },
    ],
  },
  {
    id: "daily_breath",
    type: "single",
    zone: "breath",
    maxScore: 8,
    eyebrow: "ДЫХАНИЕ В ЖИЗНИ",
    title: "КАК ТЫ ОБЫЧНО ДЫШИШЬ В ТЕЧЕНИЕ ДНЯ?",
    description: "Не во время этого теста, а в обычной жизни.",
    options: [
      { id: "calm", label: "В основном спокойно и свободно", score: 8 },
      { id: "shallow", label: "Часто замечаю поверхностное дыхание", score: 5 },
      { id: "hold", label: "Часто задерживаю дыхание или вздыхаю", score: 4 },
      { id: "breathless", label: "При небольшой нагрузке быстро появляется одышка", score: 2 },
      { id: "unknown", label: "Не обращал на это внимания", score: 4 },
    ],
  },
  {
    id: "wall_arms",
    type: "video",
    videoId: "wallArms",
    zone: "posture",
    maxScore: 12,
    eyebrow: "02 · ПЛЕЧИ И ГРУДНОЙ ОТДЕЛ",
    title: "Руки вверх у стены",
    description: "Проверь, насколько свободно поднимаются руки вверх и не приходится ли телу компенсировать движение поясницей.",
    instructions: ["Прижмите спину к стене", "Медленно поднимите прямые руки", "Не выгибайте поясницу и не задерживайте дыхание"],
    watchFor: "Руки идут вверх симметрично, рёбра не раскрываются, поясница не усиливает прогиб.",
    options: [
      { id: "clean", label: "Руки поднимаются свободно и одинаково", detail: "Поясница остаётся в спокойном положении", score: 12 },
      { id: "compensation", label: "Руки поднимаются, но поясница заметно прогибается", score: 7 },
      { id: "asymmetry", label: "Одна рука поднимается хуже другой", score: 5, asymmetry: true },
      { id: "limited", label: "Обе руки заметно ограничены", score: 3 },
      { id: "unknown", label: "Не смог оценить", score: 6 },
    ],
  },
  {
    id: "posture_symmetry",
    type: "single",
    zone: "posture",
    maxScore: 8,
    eyebrow: "СИММЕТРИЯ",
    title: "ЕСТЬ ЛИ РАЗНИЦА МЕЖДУ ПРАВОЙ И ЛЕВОЙ СТОРОНОЙ?",
    description: "Обрати внимание, одинаково ли поднимаются руки и одинаково ли ощущается движение.",
    options: [
      { id: "equal", label: "Почти одинаково", score: 8 },
      { id: "small", label: "Небольшая разница есть", score: 5, asymmetry: true },
      { id: "large", label: "Разница выраженная", score: 2, asymmetry: true },
      { id: "unknown", label: "Не могу определить", score: 4 },
    ],
  },
  {
    id: "pelvic_tilt",
    type: "video",
    videoId: "pelvicTilt",
    zone: "pelvis",
    maxScore: 14,
    eyebrow: "03 · ТАЗ И ЦЕНТР",
    title: "Наклон таза",
    description: "Попробуй плавно наклонить таз вперёд и назад. Обрати внимание, насколько легко ты контролируешь это движение.",
    instructions: ["Встаньте в привычной стойке", "Сделайте мягкий наклон таза вперёд", "Затем назад и найдите середину"],
    watchFor: "Движение таза контролируемое, без рывка и лишнего напряжения ягодиц или плеч.",
    options: [
      { id: "control", label: "Оба направления получаются легко", detail: "Движение свободное и контролируемое", score: 14 },
      { id: "one_side", label: "В одну сторону двигаться заметно легче", score: 9, asymmetry: true },
      { id: "hard", label: "Движение небольшое или появляется напряжение", score: 5 },
      { id: "none", label: "Почти не чувствую движение таза", score: 2 },
      { id: "unknown", label: "Не смог оценить", score: 7 },
    ],
  },
  {
    id: "core_control",
    type: "single",
    zone: "pelvis",
    maxScore: 6,
    eyebrow: "КОНТРОЛЬ",
    title: "УДАЁТСЯ ЛИ ДВИГАТЬ ТАЗОМ И ПРИ ЭТОМ СПОКОЙНО ДЫШАТЬ?",
    description: "Обрати внимание: не задерживаешь ли ты дыхание во время движения.",
    options: [
      { id: "yes", label: "Да, дыхание остаётся спокойным", score: 6 },
      { id: "sometimes", label: "Иногда задерживаю дыхание", score: 4 },
      { id: "no", label: "Часто сбиваюсь или напрягаюсь", score: 1 },
      { id: "unknown", label: "Не заметил / не могу определить", score: 3 },
    ],
  },
  {
    id: "overhead_squat",
    type: "video",
    videoId: "overheadSquat",
    zone: "movement",
    maxScore: 14,
    eyebrow: "04 · ПАТТЕРН ДВИЖЕНИЯ",
    title: "Присед с руками вверх",
    description: "Сделай несколько спокойных приседаний и обрати внимание, насколько легко тело сохраняет глубину, баланс и контроль.",
    instructions: ["Поставьте стопы на комфортной ширине", "Поднимите руки и выполните 2–3 приседа", "Двигайтесь только в безболезненной амплитуде"],
    watchFor: "Пятки остаются на полу, колени идут по линии стоп, корпус управляемый.",
    options: [
      { id: "clean", label: "Движение свободное и устойчивое", detail: "Приседаю без заметной потери баланса", score: 14 },
      { id: "minor", label: "Есть небольшая потеря глубины или устойчивости", score: 10 },
      { id: "compensation", label: "Пятки отрываются или корпус сильно наклоняется вперёд", score: 6 },
      { id: "asymmetry", label: "Заметно увожу вес в одну сторону", score: 4, asymmetry: true },
      { id: "symptom", label: "Появляется резкая боль или теряется контроль", score: 0, safetyFlag: "sharp_pain" },
      { id: "unknown", label: "Не смог выполнить или оценить", score: 7 },
    ],
  },
  {
    id: "stiffness",
    type: "single",
    zone: "movement",
    maxScore: 6,
    eyebrow: "Ощущение движения",
    title: "ГДЕ БЫЛО СЛОЖНЕЕ ВСЕГО ВО ВРЕМЯ ПРИСЕДА?",
    description: "Выбери то, что больше всего ограничивало движение.",
    options: [
      { id: "free", label: "Нигде, присед дался свободно", score: 6 },
      { id: "ankles", label: "Голеностопы или стопы", score: 4 },
      { id: "pelvis", label: "Тазобедренные или таз", score: 4 },
      { id: "back", label: "Спина или плечи", score: 4 },
      { id: "balance", label: "Было сложно удерживать баланс", score: 2 },
      { id: "unknown", label: "Не смог определить", score: 3 },
    ],
  },
  {
    id: "ankle_wall",
    type: "video",
    videoId: "ankleWall",
    zone: "legs",
    maxScore: 10,
    eyebrow: "05 · НОГИ И СТОПЫ",
    title: "Голеностоп: колено к стене",
    description: "Сравни правую и левую стороны: насколько свободно колено двигается вперёд, не отрывая пятку от пола.",
    instructions: ["Поставьте стопу перед стеной", "Коснитесь стены коленом, не отрывая пятку", "Повторите с другой стороны"],
    watchFor: "Пятка не отрывается, колено движется по линии стопы, стороны близки по амплитуде.",
    options: [
      { id: "equal", label: "Обе стороны двигаются свободно и примерно одинаково", score: 10 },
      { id: "minor", label: "Есть небольшое ограничение с одной стороны", score: 7, asymmetry: true },
      { id: "one", label: "Одна сторона заметно хуже другой", score: 4, asymmetry: true },
      { id: "both", label: "Обе стороны заметно ограничены", score: 2 },
      { id: "unknown", label: "Не смог выполнить или оценить", score: 5 },
    ],
  },
  {
    id: "single_leg",
    type: "video",
    videoId: "singleLeg",
    zone: "legs",
    maxScore: 10,
    eyebrow: "06 · БАЛАНС И ОПОРА",
    title: "Стойка на одной ноге",
    description: "Сравни правую и левую стороны: насколько легко удерживать равновесие без дополнительной опоры.",
    instructions: ["Встаньте рядом с опорой", "Поднимите одну стопу на 10–20 секунд", "Повторите на другой ноге"],
    watchFor: "Дыхание спокойное, таз остаётся ровным, стороны близки по устойчивости.",
    options: [
      { id: "stable", label: "Обе стороны устойчивы", detail: "Баланс удерживается спокойно", score: 10 },
      { id: "small", label: "Есть небольшое покачивание", detail: "Но равновесие сохраняется", score: 7 },
      { id: "one", label: "Одна сторона заметно менее устойчива", score: 4, asymmetry: true },
      { id: "support", label: "Без опоры удержаться сложно", score: 2 },
      { id: "symptom", label: "Возникло головокружение или резко потерял контроль", score: 0, safetyFlag: "dizziness" },
      { id: "unknown", label: "Не смог выполнить или оценить", score: 5 },
    ],
  },
  {
    id: "safety_after",
    type: "safety",
    eyebrow: "ПОСЛЕ ТЕСТА",
    title: "ПОЯВИЛОСЬ ЛИ ЧТО-ТО НОВОЕ ИЛИ НЕПРИЯТНОЕ?",
    description: "Выбери один вариант.",
    options: [
      { id: "clear", label: "Нет, всё прошло спокойно" },
      { id: "pain", label: "Появился дискомфорт или неприятные ощущения", safetyFlag: "pain" },
      { id: "sharp", label: "Появилась резкая боль", safetyFlag: "sharp_pain" },
      { id: "numb", label: "Появились онемение или покалывание", safetyFlag: "numbness" },
      { id: "dizzy", label: "Появилось головокружение", safetyFlag: "dizziness" },
      { id: "control", label: "Было ощущение резкой потери контроля", safetyFlag: "loss_of_control" },
    ],
  },
];
